import Head from "next/head";
import AboutHeader from "../components/aboutpage/AboutHeader";
import BoardMembersSection from "../components/aboutpage/BoardMembersSection";
import ByeLaws from "../components/aboutpage/ByeLaws";
import Origin from "../components/aboutpage/Origin";

export default function About() {
  return (
    <>
      <Head>
        <title>About James Udoekong Trust Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutHeader />
      <Origin />
      <BoardMembersSection />
      <ByeLaws />
    </>
  );
}
