import Head from "next/head";
import { Box, Stack, Text, Flex, Container } from "@chakra-ui/react";
import {
  SimpleGrid,
  Image,
  StackDivider,
  useColorModeValue,
} from "@chakra-ui/react";

import { FaHashtag, FaPiggyBank, FaUserAlt } from "react-icons/fa";
import React from "react";
import WrapContent from "../components/general/WrapContent";

export default function About() {
  return (
    <>
      <Head>
        <title>Donate to James Udoekong Trust Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        h="300px"
        bgImage={'url("/img/p1.jpg")'}
        bgColor={"blackAlpha.800"}
        bgBlendMode={"overlay"}
        bgRepeat={"no-repeat"}
        bgSize={"cover"}
        bgPos="center"
      >
        <WrapContent>
          <Stack h="300px" as={Flex} justifyContent={"center"}>
            <Text
              textTransform={"capitalize"}
              fontWeight={"bolder"}
              className="mfont"
              fontSize={["4xl", "4xl", "5xl", "5xl"]}
              pos={"relative"}
              color={"gray.200"}
              _before={{
                content: "''",
                position: "absolute",
                bottom: 0,
                left: 0,
                width: "64px",
                height: "4px",
                borderRadius: "2px",
                background: "#ee5c27",
              }}
              as="h1"
              py="5"
            >
              Donate
            </Text>
          </Stack>
        </WrapContent>
      </Box>
      <Container maxW="container.xl" px={8} py="20">
        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
          <Stack spacing={4}>
            <Text
              textTransform={"uppercase"}
              color={"blue.400"}
              fontWeight={600}
              fontSize={"sm"}
              bg={useColorModeValue("blue.50", "blue.900")}
              p={2}
              alignSelf={"flex-start"}
              rounded={"md"}
            >
              Be a giver!
            </Text>
            <Text as="h1" fontSize={["28px", "4xl"]} className="pfont">
              Where to donate?
            </Text>
            <Text color={"gray.500"} fontSize={"lg"}>
              Below are the details of the financial institution where donations
              will be sent and accomodated.
            </Text>
            <Stack
              spacing={4}
              divider={
                <StackDivider
                  borderColor={useColorModeValue("gray.100", "gray.700")}
                />
              }
            >
              <Stack
                direction={"row"}
                align={"center"}
                pos={"relative"}
                _after={{
                  content: "'Bank:'",
                  pos: "absolute",
                  top: "-15px",
                  left: "40px",
                  color: "gray",
                  className: "mfont",
                }}
                mt="4"
              >
                <Box>
                  <Flex
                    w={8}
                    h={8}
                    align={"center"}
                    justify={"center"}
                    rounded={"full"}
                    color="white"
                    bg={"green.500"}
                  >
                    <FaPiggyBank />
                  </Flex>
                </Box>
                <Text fontWeight={500} fontSize="20px">
                  United Bank for Africa
                </Text>
              </Stack>
              <Stack
                direction={"row"}
                align={"center"}
                pos={"relative"}
                _after={{
                  content: "'Account_name:'",
                  pos: "absolute",
                  top: "-15px",
                  left: "40px",
                  color: "gray",
                  className: "mfont",
                }}
              >
                <Box>
                  <Flex
                    w={8}
                    h={8}
                    align={"center"}
                    justify={"center"}
                    rounded={"full"}
                    bg={"blue.500"}
                    color="white"
                  >
                    <FaUserAlt />
                  </Flex>
                </Box>
                <Text fontWeight={500} fontSize="20px">
                  James Udoekong Education Trust Fund
                </Text>
              </Stack>
              <Stack
                direction={"row"}
                align={"center"}
                pos={"relative"}
                _after={{
                  content: "'Account_number:'",
                  pos: "absolute",
                  top: "-15px",
                  left: "40px",
                  color: "gray",
                  className: "mfont",
                }}
              >
                <Box>
                  <Flex
                    w={8}
                    h={8}
                    align={"center"}
                    justify={"center"}
                    rounded={"full"}
                    color="white"
                    bg={"coral"}
                  >
                    <FaHashtag />
                  </Flex>
                </Box>
                <Text fontWeight={500} fontSize="20px">
                  2004392455
                </Text>
              </Stack>
            </Stack>
          </Stack>
          <Flex h="400px" w="full" bg="red" display={["none", "none", "flex"]}>
            <Image
              rounded={"md"}
              alt={"feature image"}
              src={"/img/donate.jpg"}
              objectFit={"cover"}
              w="full"
            />
          </Flex>
        </SimpleGrid>
      </Container>
      <Box bgColor={"#3d1506"}>
        <WrapContent>
          <Stack minH="300px" as={Flex} justifyContent={"center"} py="10">
            <Text color="white" textAlign={"center"} fontSize="30px">
              We appreciate all our sponsors!
            </Text>
            <Text
              className="mfont"
              pos={"relative"}
              color={"gray.200"}
              textAlign={"center"}
            >
              This is a general community sponsorship campaign.
            </Text>
            <Text
              className="mfont"
              pos={"relative"}
              color={"gray.200"}
              textAlign={"center"}
            >
              Contributing to this campaign goes towards helping the project as
              a whole. Send us a message about your donation using our contacts
              below. Our donations are made public to promote transparency.
            </Text>
          </Stack>
        </WrapContent>
      </Box>
    </>
  );
}

// import {
//   Container,
//   SimpleGrid,
//   Image,
//   Flex,
//   Heading,
//   Text,
//   Stack,
//   StackDivider,
//   useColorModeValue,
// } from "@chakra-ui/react";

// import { FaPiggyBank } from "react-icons/fa";

// export default function Donate() {
//   return (
//     <Container maxW={"6xl"} py={"100px"}>
//       <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
//         <Stack spacing={4}>
//           <Text
//             textTransform={"uppercase"}
//             color={"blue.400"}
//             fontWeight={600}
//             fontSize={"sm"}
//             bg={useColorModeValue("blue.50", "blue.900")}
//             p={2}
//             alignSelf={"flex-start"}
//             rounded={"md"}
//           >
//             Donate
//           </Text>
//           <Heading
//             fontSize={["28px", "4xl"]}
//             fontFamily="Quicksand, -apple-system"
//           >
//             Where to donate?
//           </Heading>
//           <Text color={"gray.500"} fontSize={"lg"}>
//             Below are the details of the financial institution where donations
//             will be sent and accomodated.
//           </Text>
//           <Stack
//             spacing={4}
//             divider={
//               <StackDivider
//                 borderColor={useColorModeValue("gray.100", "gray.700")}
//               />
//             }
//           >
//             <Stack direction={"row"} align={"center"}>
//               <Flex
//                 w={8}
//                 h={8}
//                 align={"center"}
//                 justify={"center"}
//                 rounded={"full"}
//                 color="white"
//                 bg={"coral"}
//               >
//                 <FaPiggyBank />
//               </Flex>
//               <Text fontWeight={500} fontSize="20px">
//                 Bank Info Coming soon
//               </Text>
//             </Stack>
//             <Stack direction={"row"} align={"center"}>
//               <Flex
//                 w={8}
//                 h={8}
//                 align={"center"}
//                 justify={"center"}
//                 rounded={"full"}
//                 bg={"blue.500"}
//                 color="white"
//               >
//                 <FaPiggyBank />
//               </Flex>
//               <Text fontWeight={500} fontSize="20px">
//                 Bank Info Coming soon
//               </Text>
//             </Stack>
//             <Stack direction={"row"} align={"center"}>
//               <Flex
//                 w={8}
//                 h={8}
//                 align={"center"}
//                 justify={"center"}
//                 rounded={"full"}
//                 color="white"
//                 bg={"green.500"}
//               >
//                 <FaPiggyBank />
//               </Flex>
//               <Text fontWeight={500} fontSize="20px">
//                 Bank Info Coming soon
//               </Text>
//             </Stack>
//           </Stack>
//         </Stack>
//         <Flex h="400px" w="full" bg="red" display={["none", "none", "flex"]}>
//           <Image
//             rounded={"md"}
//             alt={"feature image"}
//             src={"/img/donate.jpg"}
//             objectFit={"cover"}
//             w="full"
//           />
//         </Flex>
//       </SimpleGrid>
//     </Container>
//   );
// }
