import Head from "next/head";
import { Box, Stack, Text, Flex, Container } from "@chakra-ui/react";
import React from "react";
import WrapContent from "../components/general/WrapContent";

export default function About() {
  return (
    <>
      <Head>
        <title>Our Focus at James Udoekong Trust Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        h="300px"
        bgImage={'url("/img/p1.jpg")'}
        bgColor={"blackAlpha.800"}
        bgBlendMode={"overlay"}
        bgRepeat={"no-repeat"}
        bgSize={"cover"}
        bgPos="center"
      >
        <WrapContent>
          <Stack h="300px" as={Flex} justifyContent={"center"}>
            <Text
              textTransform={"capitalize"}
              fontWeight={"bolder"}
              className="mfont"
              fontSize={["4xl", "4xl", "5xl", "5xl"]}
              pos={"relative"}
              color={"gray.200"}
              _before={{
                content: "''",
                position: "absolute",
                bottom: 0,
                left: 0,
                width: "64px",
                height: "4px",
                borderRadius: "2px",
                background: "#ee5c27",
              }}
              as="h1"
              py="5"
            >
              Our Focus
            </Text>
          </Stack>
        </WrapContent>
      </Box>
      <Container maxW="container.xl" px={8} py="20">
        <Text
          as="h1"
          textTransform={"capitalize"}
          fontWeight={"bolder"}
          className="pfont"
          color="#ee5c27"
          fontSize={["4xl", "4xl", "5xl", "5xl"]}
          textAlign={"center"}
          py="4"
        >
          Education is our focus
        </Text>
        <Box className="ofont">
          <Text as="p" p="2">
            Education is the process of acquiring knowledge, building/developing
            the powers of reasoning and sound judgment. <br />
            There are basically three types of education namely the formal,
            informal and the non-formal methods of education. While formal
            education is well structured, informal education is an unplanned,
            unstructured and does not follow a particular learning method.{" "}
          </Text>
          <Text as="p" p="2">
            The Non-formal education on its own is a structured vocational
            educational system which could be learning of skills, trade or
            programme mostly acquired and imparted consciously.
          </Text>
          <Text as="p" p="2">
            The three types of education shapes individuals and are important to
            the pyramid of growth of all individuals. These said, for any
            society to grow, Education is a key role that shapes any community.
          </Text>
          <Text as="p" p="2">
            In Aka Ikot Udo Eno, informal and the non-formal education had been
            part of the society with a lower percentage of the individuals
            acquiring formal education to the tertiary level.
          </Text>

          <Text as="p" p="2">
            Efforts from the citizens to acquire formal education from the
            Primary to the Secondary levels have been commendable despite the
            lack of Secondary School in the community. Normally, citizens living
            in Aka Ikot Udo Eno, after completion of Primary Education, go to
            nearby communities to attend Secondary School.
          </Text>
          <Text as="p" p="2">
            This therefore brought about the need for the James Udoekong
            Education Trust Fund to motivate and encourage these efforts and
            citizens of Aka Ikot Udo Eno who are passionate about furthering
            their formal education to the tertiary level but lack motivation or
            on the other hand, have limited resources to achieve this goal.
          </Text>
        </Box>
      </Container>
    </>
  );
}
