/* eslint-disable react/no-unescaped-entities */
import { Stack, Text } from "@chakra-ui/react";
import Head from "next/head";
import AboutHeader from "../components/aboutpage/AboutHeader";
import BoardMembersSection from "../components/aboutpage/BoardMembersSection";
import ByeLaws from "../components/aboutpage/ByeLaws";
import Origin from "../components/aboutpage/Origin";
import WrapContent from "../components/general/WrapContent";

export default function Founder() {
  return (
    <>
      <Head>
        <title>Founder's Bio| James Udoekong Trust Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutHeader title={"Founder's Bio"} />
      <WrapContent>
        <Stack alignItems={"center"} py="10">
          <Text as="small">ABOUT</Text>
          <Text as="h1" textAlign={"center"} fontSize="28px">
            Engineer Anthony Udoekong
          </Text>
        </Stack>
        <Text pb="5" fontSize={"18px"}>
          Obong (Engr) Anthony M. Udoekong, Iboto Ibiono Ibom is the founder and
          the life patron of James Udoekong Education Trust Fund, an NGO he
          established in year 2000 for the sole purpose of providing scholarship
          awards to the youths of Aka Ikot Udo Eno community.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          Born in Aka Ikot Udo Eno in Ibiono Ibom Local Government Area of Akwa
          Ibom State.
          <br />
          He is an accomplished engineer who has carved a niche for himself in
          his professional career. But, that is only one side of his many
          proficiencies. He is also a prolific writer with efficient
          communication skills.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          He attended St, Mary’s Practicing School, Ikot Nseyen where he passed
          his First School Leaving Certificate examination at Distinction Level.
          <br /> He proceeded to the Government Technical College, Abak, where
          he equally came out as the best graduating student in 1982.
          <br />
          He immediately got admitted into the University of Nigeria, Nsukka
          where he studied Electronic Engineering and graduated with a Second
          className honours degree in 1987.
          <br />
          <br />
          He also obtained a Master’s degree in Engineering Management from the
          University of Port Harcourt in 1998, and another Master’s degree in
          Project Management from the George Washington University, USA in 2005.
          He is a Project Management Professional (PMP), an elitist project
          management certification of The Project Management Institute of
          America.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          Engr. Udoekong was retained by Datamatics Nigeria Ltd, a computer
          engineering company in Lagos where he did his one year National Youth
          Service programme in 1988.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          He soon moved over to Societe Internationale de Telecommunications
          Aeronautiques, SITA, rising within a record time to become the
          Regional Manager West Africa before he left in 2004 to join Motorola
          as Project Manager.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          At Motorola, he again progressed rapidly up the ladder, through
          working hard and smart, to become the Systems Integration Lead for
          Sub-Sahara Africa. He decided to take his exit in 2011 to establish
          Autrax Solutions Limited engaged in telecommunication engineering
          project management and consultancy.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          He is a Member, Nigeria Society of Engineers (MNSE) and registered by
          The Council for the Regulation of Engineering in Nigeria (COREN). He
          is a former Publisher of IWADA Bulletin, a publication of Ibiono Ibom
          Welfare and Development Association, Lagos, where he once served as a
          President.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          He is a co-author of two best-selling books within Ibiono Ibom
          communities, <i>The Ibiono Ibom Compendium</i> and{" "}
          <i>
            Okuku Ime Udousoro Inyang- From Cradle to Crown ; My Trajectory to
            the Throne
          </i>
          .
          <br />
          For nearly two decades, he had served as a pivotal contributor of
          ideas and material resources to the development and evolution of Mboho
          Mkparawa Ibibio International, a pan-Ibibio socio-cultural association
          of the fourth largest tribe in Nigeria, holding various international
          executive positions.
        </Text>
        <Text pb="5" fontSize={"18px"}>
          Widely travelled, he is happily married to Ime Obong Udoekong with
          whom they have had children.
        </Text>
      </WrapContent>
    </>
  );
}
